apiVersion: database.poc.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: my-poc-db
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parameters:
    dbName: "appdb"
    owner: "raparram"
